In [1]:
from optimum.pipelines import pipeline

2023-05-12 01:34:16.528353: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-12 01:34:17.034181: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
import optimum.onnxruntime as rt

In [10]:
DistilBertTokenizerFast.*?

DistilBertTokenizerFast.SPECIAL_TOKENS_ATTRIBUTES
DistilBertTokenizerFast.__annotations__
DistilBertTokenizerFast.__base__
DistilBertTokenizerFast.__bases__
DistilBertTokenizerFast.__basicsize__
DistilBertTokenizerFast.__call__
DistilBertTokenizerFast.__class__
DistilBertTokenizerFast.__delattr__
DistilBertTokenizerFast.__dict__
DistilBertTokenizerFast.__dictoffset__
DistilBertTokenizerFast.__dir__
DistilBertTokenizerFast.__doc__
DistilBertTokenizerFast.__eq__
DistilBertTokenizerFast.__flags__
DistilBertTokenizerFast.__format__
DistilBertTokenizerFast.__ge__
DistilBertTokenizerFast.__getattribute__
DistilBertTokenizerFast.__gt__
DistilBertTokenizerFast.__hash__
DistilBertTokenizerFast.__init__
DistilBertTokenizerFast.__init_subclass__
DistilBertTokenizerFast.__instancecheck__
DistilBertTokenizerFast.__itemsize__
DistilBertTokenizerFast.__le__
DistilBertTokenizerFast.__len__
DistilBertTokenizerFast.__lt__
DistilBertTokenizerFast.__module__
DistilBertTokenizerFast.__mro__
DistilBertToken

In [48]:
import transformers
import torch

In [60]:
len(enc[0])

14

In [37]:
enc = transformers.DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')\
        .encode_plus("Robust Model Selection with Application in Single-Cell Multiomics",
                           return_tensors='pt')

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [57]:
model.pre_classifier.weight = torch.nn.Parameter(torch.eye(768))
t = torch.nn.Linear(768, 768)
t.weights = torch.nn.Parameter(torch.eye(768))
model.classifier = t

In [69]:
enc

{'input_ids': tensor([[  101, 15873,  2944,  4989,  2007,  4646,  1999,  2309,  1011,  3526,
          4800, 25524,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [29]:
enc['input_ids'].shape

torch.Size([1, 13])

In [30]:
model.distilbert(**enc)

BaseModelOutput(last_hidden_state=tensor([[[-5.7275e-01, -2.2921e-01, -2.6491e-01,  ..., -3.1681e-01,
          -7.2820e-03,  3.0555e-01],
         [-1.2105e-01,  2.9543e-04, -4.6220e-02,  ..., -1.9707e-01,
           2.6295e-01, -1.9833e-01],
         [-3.1855e-01, -2.8898e-01, -5.1896e-01,  ..., -6.5159e-01,
          -7.7686e-02,  2.7950e-01],
         ...,
         [-9.9086e-02, -2.1533e-01,  1.3529e-01,  ..., -2.0891e-01,
          -3.7595e-02, -1.3321e-01],
         [-4.5175e-01, -1.2669e-01,  3.0670e-02,  ..., -4.1114e-01,
          -1.1867e-01, -2.3275e-01],
         [ 8.2036e-01, -8.9713e-02, -5.4693e-01,  ...,  2.8454e-01,
          -8.3158e-01, -2.5317e-01]]], grad_fn=<NativeLayerNormBackward0>), hidden_states=None, attentions=None)

In [6]:
model_2 = transformers.DistilBertModel.from_pretrained('distilbert-base-uncased')

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.weight', 'vocab_layer_norm.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [56]:
model(**enc).logits.softmax(dim=-1)

tensor([[0.0687, 0.0126, 0.0424, 0.0236, 0.0069, 0.4754, 0.0124, 0.3579]],
       grad_fn=<SoftmaxBackward0>)

In [12]:
from transformers import DistilBertForSequenceClassification, DistilBertTokenizerFast
DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased').encode_plus("Hi, I'm steve")

{'input_ids': [101, 7632, 1010, 1045, 1005, 1049, 3889, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [29]:
import transformers_interpret as ti

In [44]:
tags_names = [
    'Computer Science',
    'Economics',
    'Electrical Engineering and Systems Science',
    'Mathematics',
    'Physics',
    'Quantitative Biology',
    'Quantitative Finance',
    'Statistics',
]

ti.SequenceClassificationExplainer(
    model,
    tokenizer,
    custom_labels = tags_names
)("Robust Model Selection with Application in Single-Cell Multiomics Data ")

[('[CLS]', 0.0),
 ('robust', -0.021893395973169312),
 ('model', 0.2439568101880379),
 ('selection', 0.2676956189221858),
 ('with', 0.06079675413886155),
 ('application', -0.2181278733513814),
 ('in', -0.02050738327511616),
 ('single', 0.0043712554124574945),
 ('-', -0.021099933170305653),
 ('cell', 0.03409052761700392),
 ('multi', 0.011539601688422383),
 ('##omics', 0.7696297903952544),
 ('data', -0.4717611541577463),
 ('[SEP]', 0.0)]

In [55]:
model = transformers.DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=8
)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.weight', 'vocab_layer_norm.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.bias', 'classifier.bias', 'classifier.w

In [33]:
tokenizer.encode_plus("Robust Model Selection with Application in Single-Cell Multiomics Data ", return_tensors='pt')

{'input_ids': tensor([[  101, 15873,  2944,  4989,  2007,  4646,  1999,  2309,  1011,  3526,
          4800, 25524,  2951,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [34]:
model(**tokenizer.encode_plus("Robust Model Selection with Application in Single-Cell Multiomics Data ", return_tensors='pt')).logits.softmax(dim=-1)

tensor([[0.0687, 0.0126, 0.0424, 0.0236, 0.0069, 0.4754, 0.0124, 0.3579]],
       grad_fn=<SoftmaxBackward0>)

In [16]:
import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizerFast

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=8,
    output_attentions=True
)
model.load_state_dict(torch.load("./models/01_1_field.pt"))

tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_projector.weight', 'vocab_transform.bias', 'vocab_transform.weight', 'vocab_layer_norm.bias', 'vocab_layer_norm.weight', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias', 'pre_classifier

In [4]:
import onnxruntime
onnx_path = "./models/onnx/model.onnx"
onnx_session = onnxruntime.InferenceSession(
    str(onnx_path), 
    providers=['CPUExecutionProvider']
)

In [7]:
import numpy as np
toks = tokenizer("Hi, I'm steve",
                 max_length=30, truncation=True, return_attention_mask=True,
                 return_token_type_ids=False, return_tensors='np')
feed = dict(
    input_ids=np.array(toks["input_ids"]).astype("int64"),
    attention_mask=np.array(toks["attention_mask"]).astype("int64"),
)

In [9]:
onnx_session.run(None, feed)

[array([[-1.4442513, -1.7906857, -3.9432893, -2.7414489, -2.4700718,
         -3.2154646, -2.965475 , -3.1665654]], dtype=float32)]

In [10]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
pt_model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased")

tokenizer.save_pretrained("./models/local-pt-checkpoint")
pt_model.save_pretrained("./models/local-pt-checkpoint")

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.weight', 'pre_classifier.weight', 'pre_clas

In [1]:
import tensorflow as tf
from transformers import TFDistilBertForQuestionAnswering

distilbert = TFDistilBertForQuestionAnswering.from_pretrained('distilbert-base-cased-distilled-squad')
callable = tf.function(distilbert.call)

2023-05-11 13:08:23.564021: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-11 13:08:24.066522: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


2023-05-11 13:08:48.604705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9406 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:07:00.0, compute capability: 8.6
2023-05-11 13:08:49.187145: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:637] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
All model checkpoint layers were used when initializing TFDistilBertForQuestionAnswering.

All the layers of TFDistilBertForQuestionAnswering were initialized from the model checkpoint at distilbert-base-cased-distilled-squad.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForQuestionAnswering for predictions without further training.


In [2]:
concrete_function = callable.get_concrete_function([tf.TensorSpec([None, 384], tf.int32, name="input_ids"), tf.TensorSpec([None, 384], tf.int32, name="attention_mask")])

In [3]:
tf.saved_model.save(distilbert, 'distilbert_cased_savedmodel', signatures=concrete_function)

2023-05-11 13:09:18.662922: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'inputs' with dtype float and shape [?,?,768]
	 [[{{node inputs}}]]
2023-05-11 13:09:18.668577: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'inputs' with dtype float and shape [?,?,768]
	 [[{{node inputs}}]]
2023-05-11 13:09:23.059263: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'inputs' with dtype float and shape [?,?,768]
	 [[{{node inputs}}]]
2023-05-11

INFO:tensorflow:Assets written to: distilbert_cased_savedmodel/assets


INFO:tensorflow:Assets written to: distilbert_cased_savedmodel/assets
